apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RatifyVerificationDeployment
metadata:
  name: ratify-constraint-deployment
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Deployment"]
    namespaces: ["default"]