name: Build and Publish
on:
  push:
    branches:
      - main
env:
  ACR_LOGIN_SERVER: exampleacr12345678.azurecr.io
  CERT_NAME: ratify
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/azure-voting-app-rust:${{ github.sha }} .
      - name: Aqua Security Trivy Scan
        uses: aquasecurity/trivy-action@0.10.0
        with:
          image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/azure-voting-app-rust:${{ github.sha }}
          format: table
          vuln-type: os
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/azure-voting-app-rust:${{ github.sha }}
      - name: Get Signing Key ID
        id: signingKeyId
        run: |
          ACR_NAME=$(echo $ACR_LOGIN_SERVER | cut -d. -f1)

          keyID=$(az keyvault certificate show \
          --vault-name $ACR_NAME --name ${{ env.CERT_NAME }} \
          --query "kid" --only-show-errors --output tsv)

          echo "SIGN_CERT_KEY_ID=${keyID}" >> $GITHUB_OUTPUT
      - name: Echo Signing Key Id
        run: |
          echo ${{ steps.signingKeyId.outputs.SIGN_CERT_KEY_ID }}