name: Build and Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}/azure-voting-app-rust:${{ github.sha }} .
      - name: Aqua Security Trivy Scan
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: ${{ secrets.ACR_NAME }}/azure-voting-app-rust:${{ github.sha }}
          format: table
          vuln-type: os
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL
